services:

  # MariaDB 10.9.3
  mariadb-10-9-3:
    image: mariadb:10.9.3
    container_name: mariadb-10-9-3
    ports:
      - "13306:3306"
    volumes:
      - mariadb-10-9-3:/var/lib/mysql
    networks:
      - dev_network
    command: --max_allowed_packet=32505856
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MARIADB_DATABASE: dev-database
      MARIADB_USER: dev-user
      MARIADB_PASSWORD: dev-password

  # MariaDB 10.6.16
  mariadb-10-6-16:
    image: mariadb:10.6.16
    container_name: mariadb-10-6-16
    ports:
      - "13307:3306"
    volumes:
      - mariadb-10-6-16:/var/lib/mysql
    networks:
      - dev_network
    command: --max_allowed_packet=32505856
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MARIADB_DATABASE: dev-database
      MARIADB_USER: dev-user
      MARIADB_PASSWORD: dev-password

  # Redis 7.2.4
  redis-7-2-4:
    image: redis:7.2.4-alpine
    container_name: redis-7-2-4
    ports:
      - "16379:6379"
    volumes:
      - redis-7-2-4:/data
    networks:
      - dev_network
    restart: always

  # PHP 8.2.21-fpm
  php-fpm-cf:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm-cf
    container_name: php-fpm-cf
    networks:
      - dev_network
    restart: always

  # S3Mock 3.5.2
  s3mock:
    image: adobe/s3mock:3.5.2
    container_name: s3mock
    ports:
      - "9090:9090"
      - "9091:9091"
    volumes:
      - s3mock:/data
    networks:
      - dev_network
    environment:
      - initialBuckets=test-bucket

  # S3Mock 3.6.0
  s3mock-3-6-0:
    image: adobe/s3mock:3.6.0
    container_name: s3mock-3-6-0
    ports:
      - "9092:9090"
      - "9093:9091"
    volumes:
      - s3mock-3-6-0:/data
    networks:
      - dev_network
    restart: always
    environment:
      - initialBuckets=test-bucket

  # min.io RELEASE.2024-06-29T01-20-47Z
  minio:
    image: minio/minio:RELEASE.2024-06-29T01-20-47Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    networks:
      - dev_network
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: dev-password
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 minio dev-password;
      /usr/bin/mc mb minio/testS3bucket;
      /usr/bin/mc policy set public minio/testS3bucket;
      exit 0;
      "

  # MongoDB 7.0.12
  mongo-7-0-12:
    image: mongo:7.0.12
    container_name: mongo-7-0-12
    ports:
      - 27017:27017
    volumes:
      - mongo-7-0-12:/data
    networks:
      - dev_network
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root-dev-password

volumes:
  mariadb-10-6-16:
    name: mariadb-10-6-16
  mariadb-10-9-3:
    name: mariadb-10-9-3
  redis-7-2-4:
    name: redis-7-2-4
  s3mock:
    name: s3mock
  s3mock-3-6-0:
    name: s3mock-3-6-0
  minio:
    name: minio
  mongo-7-0-12:
    name: mongo-7-0-12

networks:
  dev_network:
    name: dev_network
