version: '3.6'
services:

  # MariaDB 10.9.3
  mariadb-10-9-3:
    image: mariadb:10.9.3
    container_name: mariadb-10-9-3
    ports:
      - 13306:3306
    volumes:
      - mariadb-10-9-3:/var/lib/mysql
    networks:
      - dev_network
    command: --max_allowed_packet=32505856
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MARIADB_DATABASE: dev-database
      MARIADB_USER: dev-user
      MARIADB_PASSWORD: dev-password

  # MariaDB 10.6.16
  mariadb-10-6-16:
    image: mariadb:10.6.16
    container_name: mariadb-10-6-16
    ports:
      - 13307:3306
    volumes:
      - mariadb-10-6-16:/var/lib/mysql
    networks:
      - dev_network
    command: --max_allowed_packet=32505856
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MARIADB_DATABASE: dev-database
      MARIADB_USER: dev-user
      MARIADB_PASSWORD: dev-password

  # Redis 7.2.4
  redis-7-2-4:
    image: redis:7.2.4-alpine
    container_name: redis-7-2-4
    volumes:
      - redis-7-2-4:/data
    networks:
      - dev_network
    ports:
      - 16379:6379
    restart: always

  # PHP 8.2.14-fpm
  php-8-2-14-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-8-2-14-fpm
    container_name: php-8-2-14-fpm
    networks:
      - dev_network
    restart: always

volumes:
  mariadb-10-6-16:
    name: mariadb-10-6-16
  mariadb-10-9-3:
    name: mariadb-10-9-3
  redis-7-2-4:
    name: redis-7-2-4

networks:
  dev_network:
    name: dev_network
