FROM php:8.2.14-fpm

# > Only for debugging
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
# < Only for debugging

RUN apt-get --allow-releaseinfo-change update

RUN apt-get install -y --no-install-recommends \
    git

RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls --2 \
    && mv composer.phar /usr/local/bin/composer

RUN composer require "squizlabs/php_codesniffer"

RUN apt-get clean
